export class configurationItem {
  static data = {
    userDetails: {
      age: 25,
      name: 'Vinayak',
    },
    data: [
      {
        page: 1,
        title: 'What is your salary?',
        stepName: 'Salary Details',
        typeOfPage: 'normal_data',
        isValueField: false,
        subTitle: 'Mention your gross income',
        video: null,
        description:
          'if you don’t know what is gross pay, you can watch this video and know about it . As we say, know something before you do anything',
        fields: [
          {
            title: 'Gross Salary',
            fieldName: 'salaryStructure',
            name: 'grossSalary',
            type: 'text',
            actualValue: 120000,
            SelectedItem: null,
            placeHolder: 'please select the list',
          },
          {
            title: 'basic Salary',
            fieldName: 'salaryStructure',
            name: 'basicSalary',
            type: 'text',
            actualValue: 600000,
            SelectedItem: null,
            placeHolder: 'please select the list',
          },
        ],
        tax_data: {
          items: [],
        },
      },
      {
        page: 2,
        title: 'Do you have any savings ?',
        video: 'https://www.youtube.com/watch?v=XYy1z8mTA8E',
        stepName: 'Savings',
        typeOfPage: 'tax_data',
        isValueField: false,
        tax_data: {
          items: [
            {
              title: 'PF',
              description: 'Provident Fund',
              name: 'PF',
              actualValue: 30000,
              excemptionValue: 150000,
              category: 'sec80C',
              percentage: 30,
            },
          ],
        },
        subTitle: 'select what savings you normally do ?',
        description:
          'if you don’t know what is gross pay, you can watch this video and know about it . As we say, know something before you do anything',
        fields: [
          {
            title: 'Savings Data',
            defaultValue: 0,
            fieldName: 'sec80C',
            type: 'dropdown',
            actual: 0,
            items: [
              {
                title: 'FD',
                description: 'fixed deposit - 5 years',
                name: 'fd',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
              {
                title: 'PPF',
                description: 'Public Provident Fund',
                name: 'ppf',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
              {
                title: 'PF',
                description: 'Provident Fund',
                name: 'pf',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
              {
                title: 'vpf',
                description: 'Provident Fund',
                name: 'vpf',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
              {
                title: 'scss',
                description: 'scss Fund',
                name: 'scss',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
              {
                title: 'nsc',
                description: 'nsc Fund',
                name: 'nsc',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
              {
                title: 'taxSavingBonds',
                description: 'tax Saving Bonds Fund',
                name: 'taxSavingBonds',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
              {
                title: 'employeePensionPlan80CCD',
                description: 'employeePensionPlan80CCD Fund',
                name: 'employeePensionPlan80CCD',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
            ],
            SelectedItem: null,
            placeHolder: 'please select the list',
          },
        ],
      },
      {
        page: 3,
        title: 'Do you have any Investments ?',
        stepName: 'Investments',
        typeOfPage: 'tax_data',
        tax_data: {
          items: [],
        },
        subTitle: 'select what savings you normally do ?',
        description:
          'if you don’t know what is gross pay, you can watch this video and know about it . As we say, know something before you do anything',
        fields: [
          {
            title: 'Savings Data',
            defaultValue: 0,
            excemptionValue: 150000,
            fieldName: 'sec80C',
            type: 'dropdown',
            excemption: 150000,
            actual: 0,
            items: [
              {
                title: 'elss- mutual fund',
                description: 'elss',
                name: 'elss',
                actualValue: 0,
                excemptionValue: 30000,
                category: 'sec80C',
              },
              {
                title: 'lifeInsurance',
                description: 'life Insurance',
                name: 'lifeInsurance',
                actualValue: 0,
                excemptionValue: 30000,
                category: 'sec80C',
              },
              {
                title: 'pensionPlanMutualFunds',
                description: 'pensionPlanMutualFunds',
                name: 'pensionPlanMutualFunds',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
              {
                title: 'employeePensionPlan80CCD',
                description: 'employeePensionPlan80CCD',
                name: 'employeePensionPlan80CCD',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
              {
                title: 'SSA',
                description: 'SSA',
                name: 'SSA',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
              {
                title: 'stampDutyRegistrationChanges',
                description: 'stampDutyRegistrationChanges',
                name: 'stampDutyRegistrationChanges',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
              {
                title: 'tuitionFees',
                description: 'tuitionFees',
                name: 'tuitionFees',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'sec80C',
              },
            ],
            SelectedItem: null,
            placeHolder: 'please select the list',
          },
        ],
      },
      {
        page: 4,
        title: 'Do you have any Medical Declarations ?',
        stepName: 'Medical / Family',
        typeOfPage: 'tax_data',
        tax_data: {
          items: [],
        },
        subTitle: 'select what savings you normally do ?',
        description:
          'if you don’t know what is gross pay, you can watch this video and know about it . As we say, know something before you do anything',
        fields: [
          {
            title: 'Savings Data',
            defaultValue: 0,
            excemptionValue: 150000,
            fieldName: 'chapterVIA',
            type: 'dropdown',
            excemption: 150000,
            actual: 0,
            items: [
              {
                title: 'Medical-Self',
                description: 'Medical Insurance',
                name: 'medicalInsurancePremiumSelf80D',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'chapterVIA',
              },
              {
                title: 'Medical-Parent',
                description: 'Medical Insurance',
                name: 'medicalInsurancePremiumParents80D',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'chapterVIA',
              },
              {
                title: 'interestPaidOnEducationLoan80E',
                description: 'interestPaidOnEducationLoan80E',
                name: 'interestPaidOnEducationLoan80E',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'chapterVIA',
              },
              {
                title: 'medicalTreatmentOfHandicapDependent80DD',
                description: 'medicalTreatmentOfHandicapDependent80DD',
                name: 'medicalTreatmentOfHandicapDependent80DD',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'chapterVIA',
              },
              {
                title: 'expenditureOfSelectedMedicalTreatment80DDB',
                description: 'expenditureOfSelectedMedicalTreatment80DDB',
                name: 'expenditureOfSelectedMedicalTreatment80DDB',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'chapterVIA',
              },
              {
                title: 'donationToApprovedFunds80G80GGA80GGC',
                description: 'donationToApprovedFunds80G80GGA80GGC',
                name: 'donationToApprovedFunds80G80GGA80GGC',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'chapterVIA',
              },
              {
                title: 'rentInCaseOfNOHRAComponent80GG',
                description: 'rentInCaseOfNOHRAComponent80GG',
                name: 'rentInCaseOfNOHRAComponent80GG',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'chapterVIA',
              },
              {
                title: 'physicalDisableAssesse80U',
                description: 'physicalDisableAssesse80U',
                name: 'physicalDisableAssesse80U',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'chapterVIA',
              },
              {
                title: 'seniorCitizens80TTA',
                description: 'seniorCitizens80TTA',
                name: 'seniorCitizens80TTA',
                actualValue: 0,
                excemptionValue: 150000,
                category: 'chapterVIA',
              },
            ],
            SelectedItem: null,
            placeHolder: 'please select the list',
          },
        ],
      },
      {
        page: 5,
        title: 'Do you have any other income statements ?',
        stepName: 'Other Income',
        typeOfPage: 'tax_data',
        tax_data: {
          items: [],
        },
        subTitle: 'Other icome will be impactful on your complete data',
        description:
          'if you don’t know what is gross pay, you can watch this video and know about it . As we say, know something before you do anything',
        fields: [
          {
            title: 'Other Income Data',
            defaultValue: 0,
            excemptionValue: 0,
            fieldName: 'incomeFromOther',
            type: 'dropdown',
            excemption: 0,
            actual: 0,
            items: [
              {
                title: 'bankFD',
                description: 'bank FD',
                actualValue: 0,
                excemptionValue: 0,
                category: 'incomeFromOther',
              },
              {
                title: 'NSC',
                description: 'NSC',
                actualValue: 0,
                excemptionValue: 0,
                category: 'incomeFromOther',
              },
              {
                title: 'postOffice',
                description: 'postOffice',
                actualValue: 0,
                excemptionValue: 0,
                category: 'incomeFromOther',
              },
              {
                title: 'postOfficeRD',
                description: 'postOfficeRD',
                actualValue: 0,
                excemptionValue: 0,
                category: 'incomeFromOther',
              },
              {
                title: 'other',
                description: 'other',
                actualValue: 0,
                excemptionValue: 0,
                category: 'incomeFromOther',
              },
              {
                title: 'rent',
                description: 'rent',
                actualValue: 0,
                excemptionValue: 0,
                category: 'incomeFromOther',
              },
            ],
            SelectedItem: null,
            placeHolder: 'please select the list',
          },
        ],
      },
    ],
  };
}
